<?php

return [
    'available_avatar_sizes' => explode(',', env('API_AVAILABLE_AVATAR_SIZES', '100x100,500x500')),
    'services' => explode(',', env('API_SERVICES', 'bank,gamecenter,paybetr')),
    'bank_base_uri' => env('BANK_BASE_URI', 'https://bank.gamebetr.com'),
    'static_file_uri' => env('STATIC_FILE_URI', 'https://static.cdn1.io/playerapi/assets'),
    'affiliate_tracking_parameters' => explode(',', env('API_AFFILIATE_TRACKING_PARAMETERS', 'affiliate')),
    'debug_status_points' => env('API_DEBUG_STATUS_POINTS', false),
    'debug_betback' => env('API_DEBUG_BETBACK', false),
    'debug_affiliate' => env('API_DEBUG_AFFILIATE', false),
    'debug_winloss' => env('API_DEBUG_WINLOSS', false),
    'debug_lossback' => env('API_DEBUG_LOSSBACK', false),
    'setup_defaults' => [
        'vip_tiers' => [
            1 => [
                'name' => 'Baron III',
                'points' => 1,
                'casino_lossback' => 1,
                'sports_lossback' => 0,
                'casino_betback' => .01,
                'sports_betback' => .01,
            ],
            2 => [
                'name' => 'Baron II',
                'points' => 1000,
                'casino_lossback' => 2,
                'sports_lossback' => 1,
                'casino_betback' => .02,
                'sports_betback' => .01,
            ],
            3 => [
                'name' => 'Baron I',
                'points' => 2500,
                'casino_lossback' => 3.5,
                'sports_lossback' => 2,
                'casino_betback' => .03,
                'sports_betback' => .02,
            ],
            4 => [
                'name' => 'Knight III',
                'points' => 5000,
                'casino_lossback' => 5,
                'sports_lossback' => 3,
                'casino_betback' => .04,
                'sports_betback' => .03,
            ],
            5 => [
                'name' => 'Knight II',
                'points' => 10000,
                'casino_lossback' => 6.6,
                'sports_lossback' => 4,
                'casino_betback' => .05,
                'sports_betback' => .04,
            ],
            6 => [
                'name' => 'Knight I',
                'points' => 20000,
                'casino_lossback' => 8.3,
                'sports_lossback' => 5,
                'casino_betback' => .07,
                'sports_betback' => .05,
            ],
            7 => [
                'name' => 'Count III',
                'points' => 40000,
                'casino_lossback' => 10,
                'sports_lossback' => 6,
                'casino_betback' => .09,
                'sports_betback' => .06,
            ],
            8 => [
                'name' => 'Count II',
                'points' => 60000,
                'casino_lossback' => 11.6,
                'sports_lossback' => 7,
                'casino_betback' => .11,
                'sports_betback' => .07,
            ],
            9 => [
                'name' => 'Count I',
                'points' => 80000,
                'casino_lossback' => 13.3,
                'sports_lossback' => 8,
                'casino_betback' => .13,
                'sports_betback' => .07,
            ],
            10 => [
                'name' => 'Prince III',
                'points' => 100000,
                'casino_lossback' => 15,
                'sports_lossback' => 9,
                'casino_betback' => .15,
                'sports_betback' => .09,
            ],
            11 => [
                'name' => 'Prince II',
                'points' => 150000,
                'casino_lossback' => 16.6,
                'sports_lossback' => 10,
                'casino_betback' => .17,
                'sports_betback' => .1,
            ],
            12 => [
                'name' => 'Prince I',
                'points' => 200000,
                'casino_lossback' => 18.3,
                'sports_lossback' => 11,
                'casino_betback' => .19,
                'sports_betback' => .11,
            ],
            13 => [
                'name' => 'Duke III',
                'points' => 250000,
                'casino_lossback' => 20,
                'sports_lossback' => 12,
                'casino_betback' => .21,
                'sports_betback' => .12,
            ],
            14 => [
                'name' => 'Duke II',
                'points' => 500000,
                'casino_lossback' => 21.6,
                'sports_lossback' => 13,
                'casino_betback' => .23,
                'sports_betback' => .13,
            ],
            15 => [
                'name' => 'Duke I',
                'points' => 750000,
                'casino_lossback' => 23.3,
                'sports_lossback' => 14,
                'casino_betback' => .25,
                'sports_betback' => .14,
            ],
            16 => [
                'name' => 'King III',
                'points' => 1000000,
                'casino_lossback' => 25,
                'sports_lossback' => 15,
                'casino_betback' => .27,
                'sports_betback' => .15,
            ],
            17 => [
                'name' => 'King II',
                'points' => 2500000,
                'casino_lossback' => 27.5,
                'sports_lossback' => 16,
                'casino_betback' => .29,
                'sports_betback' => .16,
            ],
            18 => [
                'name' => 'King I',
                'points' => 5000000,
                'casino_lossback' => 30,
                'sports_lossback' => 18,
                'casino_betback' => .32,
                'sports_betback' => .18,
            ],
            19 => [
                'name' => 'Emperor',
                'points' => 10000000,
                'casino_lossback' => 33,
                'sports_lossback' => 20,
                'casino_betback' => .35,
                'sports_betback' => .2,
            ],
        ],
        'vip_points_per_casino_bet' => .2,
        'vip_points_per_sports_bet' => .1,
        'affiliate_tiers' => [
            1 => [
                'earnings' => 0,
                'casino_payout' => 20,
                'sports_payout' => 20,
            ],
            2 => [
                'earnings' => 10000,
                'casino_payout' => 25,
                'sports_payout' => 25,
            ],
            3 => [
                'earnings' => 25000,
                'casino_payout' => 30,
                'sports_payout' => 30,
            ],
            4 => [
                'earnings' => 50000,
                'casino_payout' => 40,
                'sports_payout' => 35,
            ],
            5 => [
                'earnings' => 100000,
                'casino_payout' => 50,
                'sports_payout' => 40,
            ],
        ],
        'banks' => [
            'Tether' => [
                'display_currency' => 'USDT',
                'base_currency' => 'MICROCENT',
                'deposit_currency' => 'USDT',
            ],
            'Decimilli Bitcoin' => [
                'display_currency' => 'DMBTC',
                'base_currency' => 'SATOSHI',
                'deposit_currency' => 'BTC',
            ],
            'Centi Litecoin' => [
                'display_currency' => 'CLTC',
                'base_currency' => 'SATOSHI',
                'deposit_currency' => 'LTC',
            ],
            'Centi Bitcoin Cash' => [
                'display_currency' => 'CBCH',
                'base_currency' => 'SATOSHI',
                'deposit_currency' => 'BCH',
            ],
            'Centi Dash' => [
                'display_currency' => 'CDASH',
                'base_currency' => 'SATOSHI',
                'deposit_currency' => 'DASH',
            ],
            'Deka Doge' => [
                'display_currency' => 'DADOGE',
                'base_currency' => 'SATOSHI',
                'deposit_currency' => 'DOGE',
            ],
            'Milli Ethereum' => [
                'display_currency' => 'METH',
                'base_currency' => 'GWEI',
                'deposit_currency' => 'ETH',
            ],
            'Mega Shiba Inu' => [
                'display_currency' => 'MESHIB',
                'base_currency' => 'GWEI',
                'deposit_currency' => 'SHIB',
            ],
            'Ripple' => [
                'display_currency' => 'XRP',
                'base_currency' => 'DROP',
                'deposit_currency' => 'XRP',
            ],
            'Centi Monero' => [
                'display_currency' => 'CXMR',
                'base_currency' => 'NANONERO',
                'deposit_currency' => 'XMR',
            ],
        ],
    ],
];
